title: Ranjith Kumar M G
logo: /ranjith.jpg
#description: text below image
show_downloads: true
#description: Resume of Ranjith Kumar MG
#baseurl: ""
#url: "https://ranjith8747.github.io"
theme: jekyll-theme-minimal
